services:

  #Controllers

  talented_panda.puzzle_problem.controller.puzzle:
    class: TalentedPanda\PuzzleProblem\Controller\PuzzleController
    arguments:
      - '@talented_panda.puzzle_problem.service.match_finder'
      - '@talented_panda.puzzle_problem.service.puzzle_solver'

  #Services

  talented_panda.puzzle_problem.service.input_handler:
    class: TalentedPanda\PuzzleProblem\Service\InputHandler
    arguments:
      - '@talented_panda.puzzle_problem.service.file_manager'

  talented_panda.puzzle_problem.service.file_manager:
    class: TalentedPanda\PuzzleProblem\Service\FileManager
    arguments:
      - '%default_puzzle_path%'

  talented_panda.puzzle_problem.service.match_finder:
    class: TalentedPanda\PuzzleProblem\Service\MatchFinder

  talented_panda.puzzle_problem.service.puzzle_solver:
    class: TalentedPanda\PuzzleProblem\Service\PuzzleSolver
    arguments:
      - '@talented_panda.puzzle_problem.service.match_finder'